### ISSUE TITLE
NOTE: python-bitcointx depencency: python package rename from 'bitcoin' to 'bitcointx'

### ISSUE THREAD

**Issue by dgpv** [citp/testchain-generator#1]
You are using https://github.com/Simplexum/python-bitcointx.git in your requirements.txt

Please note that python-bitcointx transition to the independent derivative library from python-bitcoinlib is not yet finished. The python package will be renamed from 'bitcoin' to 'bitcointx' in the near future (https://github.com/Simplexum/python-bitcointx/issues/7), and use_libsecp256k1_for_signing() function will probably be gone, because libsecp256k1 will be the default.

**Comment by maltemoeser** [comment]
Thanks for the heads up. I've chosen your fork since it added all the changes to python-bitcoinlib that I needed to get this project running (and I didn't want to maintain another fork, for now at least). I'll keep an eye out on the changes you are making.

**Comment by maltemoeser** [comment]
For now, I've pinned bitcointx to the last commit so that any changes made shouldn't immediately affect us
